# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_trader', [dirname(__file__)])
        except ImportError:
            import _trader
            return _trader
        if fp is not None:
            try:
                _mod = imp.load_module('_trader', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _trader = swig_import_helper()
    del swig_import_helper
else:
    import _trader
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _trader.delete_SwigPyIterator
    __del__ = lambda self : None;
    def value(self): return _trader.SwigPyIterator_value(self)
    def incr(self, n = 1): return _trader.SwigPyIterator_incr(self, n)
    def decr(self, n = 1): return _trader.SwigPyIterator_decr(self, n)
    def distance(self, *args): return _trader.SwigPyIterator_distance(self, *args)
    def equal(self, *args): return _trader.SwigPyIterator_equal(self, *args)
    def copy(self): return _trader.SwigPyIterator_copy(self)
    def next(self): return _trader.SwigPyIterator_next(self)
    def __next__(self): return _trader.SwigPyIterator___next__(self)
    def previous(self): return _trader.SwigPyIterator_previous(self)
    def advance(self, *args): return _trader.SwigPyIterator_advance(self, *args)
    def __eq__(self, *args): return _trader.SwigPyIterator___eq__(self, *args)
    def __ne__(self, *args): return _trader.SwigPyIterator___ne__(self, *args)
    def __iadd__(self, *args): return _trader.SwigPyIterator___iadd__(self, *args)
    def __isub__(self, *args): return _trader.SwigPyIterator___isub__(self, *args)
    def __add__(self, *args): return _trader.SwigPyIterator___add__(self, *args)
    def __sub__(self, *args): return _trader.SwigPyIterator___sub__(self, *args)
    def __iter__(self): return self
SwigPyIterator_swigregister = _trader.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class Trader(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Trader, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Trader, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _trader.new_Trader(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _trader.delete_Trader
    __del__ = lambda self : None;
    def buy(self, *args): return _trader.Trader_buy(self, *args)
    def sell(self, *args): return _trader.Trader_sell(self, *args)
    def update_position_info(self): return _trader.Trader_update_position_info(self)
    def get_position_info(self): return _trader.Trader_get_position_info(self)
    def update_account_info(self): return _trader.Trader_update_account_info(self)
    def get_account_info(self): return _trader.Trader_get_account_info(self)
    def update_trade_records(self): return _trader.Trader_update_trade_records(self)
    def get_trade_records(self): return _trader.Trader_get_trade_records(self)
    def IsErrorRspInfo(self, *args): return _trader.Trader_IsErrorRspInfo(self, *args)
    def get_error_msg(self): return _trader.Trader_get_error_msg(self)
Trader_swigregister = _trader.Trader_swigregister
Trader_swigregister(Trader)



